/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitaldiary;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author aks
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTf = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        passFld = new javax.swing.JPasswordField();
        confPassFld = new javax.swing.JPasswordField();
        btnProceed = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New User Registration");
        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(560, 490));
        setSize(new java.awt.Dimension(542, 321));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        nameTf.setForeground(new java.awt.Color(192, 190, 212));
        nameTf.setText("Name");
        nameTf.setToolTipText("");
        nameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTfFocusGained(evt);
            }
        });
        getContentPane().add(nameTf);
        nameTf.setBounds(280, 90, 250, 22);

        email.setForeground(new java.awt.Color(192, 190, 212));
        email.setText("Email");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(280, 230, 250, 22);

        phone.setForeground(new java.awt.Color(192, 190, 212));
        phone.setText("Phone Number");
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
        });
        getContentPane().add(phone);
        phone.setBounds(280, 270, 250, 22);

        gender.setForeground(new java.awt.Color(192, 190, 212));
        gender.setText("Male/Female");
        gender.setToolTipText("");
        gender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                genderFocusGained(evt);
            }
        });
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        getContentPane().add(gender);
        gender.setBounds(280, 310, 250, 22);

        passFld.setForeground(new java.awt.Color(192, 190, 212));
        passFld.setText("Password");
        passFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFldFocusGained(evt);
            }
        });
        getContentPane().add(passFld);
        passFld.setBounds(280, 130, 250, 22);

        confPassFld.setForeground(new java.awt.Color(192, 190, 212));
        confPassFld.setText("Password");
        confPassFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confPassFldFocusGained(evt);
            }
        });
        getContentPane().add(confPassFld);
        confPassFld.setBounds(280, 180, 250, 22);

        btnProceed.setText("Proceed ");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });
        getContentPane().add(btnProceed);
        btnProceed.setBounds(360, 410, 100, 25);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 130, 100, 30);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Confirm Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 180, 190, 30);

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 90, 90, 30);

        jLabel4.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel4.setText("Email ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 230, 100, 20);

        jLabel5.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel5.setText("Phone Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 270, 160, 22);

        jLabel6.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 310, 120, 30);
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       String image[]={"image1.png", "image2.png", "image3.png", "image4.png", "image5.png"};
        Random r= new Random();
        double a=Math.random()*4;
        int i=(int)a;

        backgroundLabel.setIcon(new ImageIcon(image[i]));
    }//GEN-LAST:event_formWindowOpened

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        String name=nameTf.getText().trim();
        String pass=new String(passFld.getPassword());
        String confPass=new String(confPassFld.getPassword());
        String emil=email.getText().trim();
       String phon=phone.getText().trim();
       String gndr=gender.getText().trim();
      
        
        if(!(new File(System.getProperty("user.home")+"/Documents/DigitalDiary/")).exists())
            new File(System.getProperty("user.home")+"/Documents/DigitalDiary/").mkdir();
        
        System.out.println(""+pass);
        System.out.println(""+confPass);
         System.out.println(""+emil);
        System.out.println(""+phon);
         System.out.println(""+gndr);
        
        if(!(name==null || name.isEmpty())&& !(emil==null || emil.isEmpty())&& !(phon==null || phon.isEmpty())&& !(gndr==null || gndr.isEmpty()))
        {
            if(pass.equals(confPass))
            {
                try
                {
                    BufferedWriter bw=new BufferedWriter(new FileWriter(".authen.dat"));
                    bw.write(name);
                    bw.newLine();
                    bw.write(pass);
                    bw.newLine();
                    bw.write(emil);
                    bw.newLine();
                    bw.write(phon);
                    bw.newLine();
                    bw.write(gndr);
                    bw.close();
                    NoteMaker nm=new NoteMaker();
                    nm.setVisible(true);
                    this.dispose();
                }
                catch(Exception e)
                {
                    System.out.println("Could not make file");
                    e.printStackTrace();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Passwords Do not match");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "All fields are required to be filled");
        }
        
    }//GEN-LAST:event_btnProceedActionPerformed

    private void nameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTfFocusGained
        if(nameTf.getText().equals("Name"))
        {
            nameTf.setForeground(new java.awt.Color(44, 44, 44));
            nameTf.setText("");
        }
       
       
      
    }//GEN-LAST:event_nameTfFocusGained

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_emailActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
           if(email.getText().equals("Email"))
        {
            email.setForeground(new java.awt.Color(44, 44, 44));
            email.setText("");
        }
    }//GEN-LAST:event_emailFocusGained

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        // TODO add your handling code here:
         if(phone.getText().equals("Phone Number"))
        {
            phone.setForeground(new java.awt.Color(44, 44, 44));
            phone.setText("");
        }
    }//GEN-LAST:event_phoneFocusGained

    private void genderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_genderFocusGained
        // TODO add your handling code here:
          if(gender.getText().equals("Male/Female"))
        {
            gender.setForeground(new java.awt.Color(44, 44, 44));
            gender.setText("");
        }
    }//GEN-LAST:event_genderFocusGained

    private void passFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFldFocusGained
        // TODO add your handling code here:
           if(passFld.getText().equals("Password"))
        {
            passFld.setForeground(new java.awt.Color(44, 44, 44));
            passFld.setText("");
        }
    }//GEN-LAST:event_passFldFocusGained

    private void confPassFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confPassFldFocusGained

        // TODO add your handling code here:
        
           if(confPassFld.getText().equals("Password"))
        {
            confPassFld.setForeground(new java.awt.Color(44, 44, 44));
            confPassFld.setText("");
        }
    }//GEN-LAST:event_confPassFldFocusGained

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton btnProceed;
    private javax.swing.JPasswordField confPassFld;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameTf;
    private javax.swing.JPasswordField passFld;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
